run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
  disable:
    - structcheck
    - varcheck
    - deadcode
  fast: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    check-shadowing: false

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # 排除测试文件的某些检查
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # 排除生成的代码
    - path: api/swagger/
      linters:
        - all

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
